### ISSUE TITLE
Update the restricted countries list

### ISSUE THREAD

**Issue by jeffkause** [cisagov/cyhy-core#90]
# 💡 Summary #

CISA has released a new restricted countries list which needs to be incorporated into cyhy-core.

## Motivation and context ##

This will increase our security and notify us of any restricted IP address during the on-boarding process.

## Implementation notes ##

Update the `RESTRICTED_COUNTRIES` list inside of `geoloc.py`:
https://github.com/cisagov/cyhy-core/blob/6d1befcb8e3719c64bd96e5f3b25af8c9708c149/cyhy/core/geoloc.py#L12

**Updated Countries List:**
Will be sent to the DEV team.

## Acceptance criteria ##

How do we know when this work is done?

- [x] The list has been updated
- [x] A sample IP list demonstrates the updated restricted list is being flagged.

**Comment by jsf9k** [comment]
@jeffkause - If you can send me the updated list before noon Friday then I can make this change this week.

**Comment by jeffkause** [comment]
Just sent via chat.

**Comment by jsf9k** [comment]
@jeffkause - @dav3r said that you were working on this, so I reassigned the issue to you.
